#!/bin/bash
rm -rf debug1_1 debug1_2 debug1_3 debug1_4 debug1_5 debug1_6 debug1_7 debug1_8 debug1_9 debug1_10 debug1_11
promise --precs=chsd --nbDigits=1
mv debug debug1_1
promise --precs=chsd --nbDigits=2
mv debug debug1_2
promise --precs=chsd --nbDigits=3
mv debug debug1_3
promise --precs=chsd --nbDigits=4
mv debug debug1_4
promise --precs=chsd --nbDigits=5
mv debug debug1_5
promise --precs=chsd --nbDigits=6
mv debug debug1_6
promise --precs=chsd --nbDigits=7
mv debug debug1_7
promise --precs=chsd --nbDigits=8
mv debug debug1_8
promise --precs=chsd --nbDigits=9
mv debug debug1_9
promise --precs=chsd --nbDigits=10
mv debug debug1_10
promise --precs=chsd --nbDigits=11
mv debug debug1_11

rm -rf debug2_1 debug2_2 debug2_3 debug2_4 debug2_5 debug2_6 debug2_7 debug2_8 debug2_9 debug2_10 debug2_11
promise --precs=whsd --nbDigits=1
mv debug debug2_1
promise --precs=whsd --nbDigits=2
mv debug debug2_2
promise --precs=whsd --nbDigits=3
mv debug debug2_3
promise --precs=whsd --nbDigits=4
mv debug debug2_4
promise --precs=whsd --nbDigits=5
mv debug debug2_5
promise --precs=whsd --nbDigits=6
mv debug debug2_6
promise --precs=whsd --nbDigits=7
mv debug debug2_7
promise --precs=whsd --nbDigits=8
mv debug debug2_8
promise --precs=whsd --nbDigits=9
mv debug debug2_9
promise --precs=whsd --nbDigits=10
mv debug debug2_10
promise --precs=whsd --nbDigits=11
mv debug debug2_11

rm -rf debug3_1 debug3_2 debug3_3 debug3_4 debug3_5 debug3_6 debug3_7 debug3_8 debug3_9 debug3_10 debug3_11
promise --precs=cbsd --nbDigits=1
mv debug debug3_1
promise --precs=cbsd --nbDigits=2
mv debug debug3_2
promise --precs=cbsd --nbDigits=3
mv debug debug3_3
promise --precs=cbsd --nbDigits=4
mv debug debug3_4
promise --precs=cbsd --nbDigits=5
mv debug debug3_5
promise --precs=cbsd --nbDigits=6
mv debug debug3_6
promise --precs=cbsd --nbDigits=7
mv debug debug3_7
promise --precs=cbsd --nbDigits=8
mv debug debug3_8
promise --precs=cbsd --nbDigits=9
mv debug debug3_9
promise --precs=cbsd --nbDigits=10
mv debug debug3_10
promise --precs=cbsd --nbDigits=11
mv debug debug3_11

rm -rf debug4_1 debug4_2 debug4_3 debug4_4 debug4_5 debug4_6 debug4_7 debug4_8 debug4_9 debug4_10 debug4_11
promise --precs=wbsd --nbDigits=1
mv debug debug4_1
promise --precs=wbsd --nbDigits=2
mv debug debug4_2
promise --precs=wbsd --nbDigits=3
mv debug debug4_3
promise --precs=wbsd --nbDigits=4
mv debug debug4_4
promise --precs=wbsd --nbDigits=5
mv debug debug4_5
promise --precs=wbsd --nbDigits=6
mv debug debug4_6
promise --precs=wbsd --nbDigits=7
mv debug debug4_7
promise --precs=wbsd --nbDigits=8
mv debug debug4_8
promise --precs=wbsd --nbDigits=9
mv debug debug4_9
promise --precs=wbsd --nbDigits=10
mv debug debug4_10
promise --precs=wbsd --nbDigits=11
mv debug debug4_11
