#!/bin/bash
rm -rf prec2 prec4 prec6 prec8

promise --precs=wpsd --nbDigits=1
mv debug prec1_1
promise --precs=wpsd --nbDigits=2
mv debug prec1_2
promise --precs=wpsd --nbDigits=3
mv debug prec1_3
promise --precs=wpsd --nbDigits=4
mv debug prec1_4
promise --precs=wpsd --nbDigits=5
mv debug prec1_5
promise --precs=wpsd --nbDigits=6
mv debug prec1_6
promise --precs=wpsd --nbDigits=7
mv debug prec1_7
promise --precs=wpsd --nbDigits=8
mv debug prec1_8
promise --precs=wpsd --nbDigits=9
mv debug prec1_9
promise --precs=wpsd --nbDigits=10
mv debug prec1_10

promise --precs=wbsd --nbDigits=1
mv debug prec2_1
promise --precs=wbsd --nbDigits=2
mv debug prec2_2
promise --precs=wbsd --nbDigits=3
mv debug prec2_3
promise --precs=wbsd --nbDigits=4
mv debug prec2_4
promise --precs=wbsd --nbDigits=5
mv debug prec2_5
promise --precs=wbsd --nbDigits=6
mv debug prec2_6
promise --precs=wbsd --nbDigits=7
mv debug prec2_7
promise --precs=wbsd --nbDigits=8
mv debug prec2_8
promise --precs=wbsd --nbDigits=9
mv debug prec2_9
promise --precs=wbsd --nbDigits=10
mv debug prec2_10

promise --precs=cpsd --nbDigits=1
mv debug prec3_1
promise --precs=cpsd --nbDigits=2
mv debug prec3_2
promise --precs=cpsd --nbDigits=3
mv debug prec3_3
promise --precs=cpsd --nbDigits=4
mv debug prec3_4
promise --precs=cpsd --nbDigits=5
mv debug prec3_5
promise --precs=cpsd --nbDigits=6
mv debug prec3_6
promise --precs=cpsd --nbDigits=7
mv debug prec3_7
promise --precs=cpsd --nbDigits=8
mv debug prec3_8
promise --precs=cpsd --nbDigits=9
mv debug prec3_9
promise --precs=cpsd --nbDigits=10
mv debug prec3_10

promise --precs=cbsd --nbDigits=1
mv debug prec4_1
promise --precs=cbsd --nbDigits=2
mv debug prec4_2
promise --precs=cbsd --nbDigits=3
mv debug prec4_3
promise --precs=cbsd --nbDigits=4
mv debug prec4_4
promise --precs=cbsd --nbDigits=5
mv debug prec4_5
promise --precs=cbsd --nbDigits=6
mv debug prec4_6
promise --precs=cbsd --nbDigits=7
mv debug prec4_7
promise --precs=cbsd --nbDigits=8
mv debug prec4_8
promise --precs=cbsd --nbDigits=9
mv debug prec4_9
promise --precs=cbsd --nbDigits=10
mv debug prec4_10
